### ISSUE TITLE
Ability to crop and enlarge camera images

### ISSUE THREAD

**Issue by Cdetviler** [aprsworld/wsWebDisplay#1]

**Comment by kb0thn** [comment]
Example JQuery library:
http://fengyuanchen.github.io/cropper/

On 9/21/2015 4:05 PM, Charlie Detviler wrote:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/aprsworld/wsWebDisplay/issues/1.

## 

-James Jefferson Jarvis
APRS World, LLC
+1-507-454-2727
www.aprsworld.com
