### ISSUE TITLE
Ability to supress hover-image when camera-image size is greater than or equal to native

### ISSUE THREAD

**Issue by Cdetviler** [aprsworld/wsWebDisplay#32]

**Comment by kb0thn** [comment]
Or same size

On 11/12/2015 3:40 PM, Charlie Detviler wrote:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/aprsworld/wsWebDisplay/issues/32.

## 

-James Jefferson Jarvis
APRS World, LLC
+1-507-454-2727
www.aprsworld.com

**Comment by Cdetviler** [comment]
This enhancement has been added
