### ISSUE TITLE
Drag coordinates are appearing as large decimal numbers sometimes

### ISSUE THREAD

**Issue by Cdetviler** [aprsworld/wsWebDisplay#33]

**Comment by Cdetviler** [comment]
It seems to be caused when the user resizes with the top-left corner. Since the top left corner is also what is used for positioning (top and left), the positioning coordinates will be set to wherever the top-left corner was left at. If the resize ended at a top 102.34657 and 600.345246, then the position coordinates will be set to 102.34657 and 600.345246. The change that I made should fix the issue. I forced the resize to work on a 1,1 grid which should eliminate the possibility of decimals. I have tested quite a few cams now, and the bug does not seem to be occurring since the change. I will keep the issue open a little longer just in case.

**Comment by kb0thn** [comment]
Now I don't get any drag coordinates.

On 11/13/2015 9:02 AM, Charlie Detviler wrote:

> It seems to be caused when the user resizes with the top-left corner.
> Since the top left corner is also what is used for positioning (top and
> left), the positioning coordinates will be set to wherever the top-left
> corner was left at. If the resize ended at a top 102.34657 and
> 600.345246, then the position coordinates will be set to 102.34657 and
> 600.345246. The change that I made should fix the issue. I forced the
> resize to work on a 1,1 grid which should eliminate the possibility of
> decimals. I have tested quite a few cams now, and the bug does not seem
> to be occurring since the change. I will keep the issue open a little
> longer just in case.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aprsworld/wsWebDisplay/issues/33#issuecomment-156454879.

## 

-James Jefferson Jarvis
APRS World, LLC
+1-507-454-2727
www.aprsworld.com

**Comment by Cdetviler** [comment]
This is no longer happening now that everything is attached to a main grid. Even if the element is resized it will snap to the grid the next time it is moved.
