### ISSUE TITLE
dragging from tree - need to align better when dropping

### ISSUE THREAD

**Issue by Cdetviler** [aprsworld/wsWebDisplay#38]
Currently there is a stair-stepping issue when dropping elements in

**Comment by Cdetviler** [comment]
I think this stems from the way that the "preview" cell works. Currently, the preview cell only has the styling of a data cell, but does not have the data associated with the cell that is yet to be created. When the actual cell is created upon drop, then it is granted all of the attributes associated with the data and the length and height adjust according to the content within the container, making it seem like it changed position. A solution to this might be to have the preview cell be an exact replica.

**Comment by Cdetviler** [comment]
Dragging now is accompanied with guiding lines and a grid that elements snap to. Elements dragged from the tree are still placed freely from the grid. I am going to try to make them snap to the grid while in the process of being dragged from the tree.

**Comment by kb0thn** [comment]
Good plan. That's what we want.

On 12/2/2015 10:06 AM, Charlie Detviler wrote:

> Dragging now is accompanied with guiding lines and a grid that elements
> snap to. Elements dragged from the tree are still placed freely from the
> grid. I am going to try to make them snap to the grid while in the
> process of being dragged from the tree.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aprsworld/wsWebDisplay/issues/38#issuecomment-161346285.

## 

-James Jefferson Jarvis
APRS World, LLC
+1-507-454-2727
www.aprsworld.com

**Comment by Cdetviler** [comment]
Changed the way adding cells and cameras to the page works. There is now a plus next to every item in the tree. When this plus is clicked, an element attaches to the mouse cursor and will snap to the gridlines as the mouse is dragged. This allows for much better precision when placing elements.
