### ISSUE TITLE
Missing gridlines in all browsers at various zoom levels

### ISSUE THREAD

**Issue by Cdetviler** [aprsworld/wsWebDisplay#41]
I will have to test it on the windows desktop, because I cannot replicate the issue in linux firefox.

**Comment by Cdetviler** [comment]
I was able to reproduce the issue by zooming out with the browser. Upon inspecting the gridline element, I found that it is still on the page, it is just not showing. The css is the same for all the gridlines. It is set to display block with a width of 1 px. I will have to investigate causes for this.

![screenshot from 2015-12-04 09 02 45](https://cloud.githubusercontent.com/assets/12413097/11592745/0a2db030-9a66-11e5-9b61-6346d12e6c85.png)

**Comment by Cdetviler** [comment]
It seems to be a rendering issue with browsers. All of these grid lines are at a width of 1px. When the browser is resized the width drops below 1px and some of them do not show. This seems to be a common issue across all browsers and is reported as a bug quite a bit.

https://bugzilla.mozilla.org/show_bug.cgi?id=176237

This guy is having the same exact issue when he tries to make a grid:

http://stackoverflow.com/questions/33740182/how-to-fix-zoom-issues-with-google-chrome-and-1px-width-height-divs

**Comment by kb0thn** [comment]
well, I like using firefox. Can you either make the lines thicker for 
everyone or do a browser specific work around for firefox?

I think you could also do the grid with a repeating background image. 
Say you had a 50x50 grid. Do an image that is 49x49 and has a line down 
the left hand side and a line across the top. Then repeat horizontally 
and vertically.

On 12/4/2015 9:58 AM, Charlie Detviler wrote:

> It seems to be a rendering issue with firefox. All of these grid lines
> are at a width of 1px. When the browser is resized the width drops below
> 1px and some of them do not show. This seems to be a common issue across
> all browsers and is reported as a bug quite a bit.
> 
> https://bugzilla.mozilla.org/show_bug.cgi?id=176237
> 
> This guy is having the same exact issue when he tries to make a grid:
> 
> http://stackoverflow.com/questions/33740182/how-to-fix-zoom-issues-with-google-chrome-and-1px-width-height-divs
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aprsworld/wsWebDisplay/issues/41#issuecomment-162004467.

## 

-James Jefferson Jarvis
APRS World, LLC
+1-507-454-2727
www.aprsworld.com

**Comment by Cdetviler** [comment]
I am trying to brainstorm some solutions. The image idea is interesting. I will try that next.

**Comment by Cdetviler** [comment]
This was fixed by changing the gridlines to colored borders instead of width with background color. Borders seem to handle resizing much better.
