### ISSUE TITLE
Manual Entry for element sizing

### ISSUE THREAD

**Issue by Cdetviler** [aprsworld/wsWebDisplay#81]
There should be fields in the edit window that allow for manual editing of an elements size. Furthermore, these fields should be pre-populated with the dimensions of the last element that was edited.

**Comment by Cdetviler** [comment]
If it is the first element edited, perhaps it should be populated with the default dimensions for that element?

**Comment by kb0thn** [comment]
On 2/3/2016 10:32 AM, Charlie Detviler wrote:

> There should be fields in the edit window that allow for manual editing
> of an elements size. Furthermore, these fields should be pre-populated
> with the dimensions of the last element that was edited.

The sizing should only take effect when an "apply" or "set size" button 
is clicked.

> —
> Reply to this email directly or view it on GitHub
> https://github.com/aprsworld/wsWebDisplay/issues/81.

## 

-James Jefferson Jarvis
APRS World, LLC
+1-507-454-2727
www.aprsworld.com

**Comment by kb0thn** [comment]
Andrew suggests that we don't have it automatically pre-populate the 
manual size field with the last value. It should pre-populate with the 
current size of the element. But we should have a button above or to the 
left of the size input boxes that is "Use last element size" or the 
like. And then below or to the right an apply button.

On 2/3/2016 10:32 AM, Charlie Detviler wrote:

> If it is the first element edited, perhaps it should be populated with
> the default dimensions for that element?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aprsworld/wsWebDisplay/issues/81#issuecomment-179326203.

## 

-James Jefferson Jarvis
APRS World, LLC
+1-507-454-2727
www.aprsworld.com

**Comment by Cdetviler** [comment]
So I have implemented this feature as I interpreted it. Here is how it works:

Text blocks objects and Cells objects are placed into a two-position queue within the page-settings object when they are selected in edit mode. If the same object is clicked on multiple times, there is logic that prevents it from occupying both indexes of the queue. Two fields in the edit-pane are populated with the width and height. These fields can be manually changed and applied when the "apply dimensions" button is pressed. The user can also click the "use last element's dimensions" button and the fields will populate with the dimensions of the element at position 0 in the queue (in other words, the previous element) - these values will not apply until the user clicks the "apply dimensions" button.

Unfortunately, the addition of this has cluttered up the edit-pane. One some screen sizes, things will appear off-screen. I am going to have to come up with a solution to deal with this. I will be opening a feature request shortly.

**Comment by Cdetviler** [comment]
Jim suggested that width and height can be adjusted separately. This would allow images and cameras to be adjusted based on their aspect ratio.

**Comment by Cdetviler** [comment]
The css for this is also not finalized. It currently looks pretty ugly. That is related to issue #83

**Comment by Cdetviler** [comment]
The CSS has been improved and a new issue (#88) has been opened with the separate width and height resizing feature request.
