### ISSUE TITLE
Allow for width and height to be grabbed from previous element seperately

### ISSUE THREAD

**Issue by Cdetviler** [aprsworld/wsWebDisplay#88]
This would allow for the automatic resizing of camera and image elements without messing up the aspect ratio

**Comment by kb0thn** [comment]
Fine for images, but I think for text getting both in one button click 
is nicer

On 2/18/2016 9:54 AM, Charlie Detviler wrote:

> This would allow for the automatic resizing of camera and image elements
> without messing up the aspect ratio
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aprsworld/wsWebDisplay/issues/88.

## 

-James Jefferson Jarvis
APRS World, LLC
+1-507-454-2727
www.aprsworld.com
