### ISSUE TITLE
when camera image can't load initially, it never loads

### ISSUE THREAD

**Issue by kb0thn** [aprsworld/wsWebDisplay#89]
so when pi camera first starts up, an image may not be available. IE no entry in tree. But then a minute later, it will be in tree. But wsWebDisplay never picks it up. Reloading the page / configuration causes it to come up.

It should gracefully handle a camera in saved config but not yet in the live data tree.

**Comment by Cdetviler** [comment]
I added a placeholder image that loads when the path is undefined. I also changed the function that updates the data object so that it will properly add properties if they did not exist prior to the update. There were some scenarios where this would not happen.
